version: 2.1
jobs:
  publish_and_release:
    docker:
      - image: circleci/openjdk:latest
    working_directory: ~/code
    steps:
      - checkout
      - restore_cache:
          key: sbt-cache-0
      - add_ssh_keys:
          fingerprints:
            - "2f:63:7c:30:5f:96:d3:c1:69:43:ce:e1:ae:b3:b1:60"
      - run:
          name: Import GPG Key
          command: echo -e "$GPG_SECRET" | gpg --import
      - run:
          name: Set Git Config
          command: |
            git push --set-upstream origin master
            git config --global user.email "shadowrhyder@gmail.com"
            git config --global user.name "Richard"
      - run:
          name: Compile JAR
          command: sbt 'release with-defaults'
      - save_cache:
          key: sbt-cache-0
          paths:
            - "~/.m2"
            - "~/.sbt"
            - "~/.ivy2/cache"
workflows:
  deployment:
    jobs:
      - publish_and_release:
          context:
            - Sonatype
          filters:
            branches:
              only:
                - master