version: 2.1
jobs:
  publish_and_release:
    docker:
      - image: circleci/openjdk:latest
    working_directory: ~/code
    steps:
      - checkout
      - restore_cache:
          key: sbt-cache-0
      - add_ssh_keys:
          fingerprints:
            - "c8:2c:ff:72:c4:ed:47:51:3a:26:30:92:b7:a2:d1:3a"
      - run:
          name: Import PGP Key
          command: |
            sudo rm -rf /var/lib/apt/lists/* && sudo apt-get update
            sudo apt-get install -y dos2unix
            echo -e "$PGP_KEY" > key.asc
            dos2unix key.asc
            gpg --import key.asc
      - run:
          name: Set Git Config
          command: |
            git push --set-upstream origin master
            git config --global user.email "stuartjmsn3@gmail.com"
            git config --global user.name "Stuart"
      - run:
          name: Compile JAR
          command: sbt 'release with-defaults'
      - save_cache:
          key: sbt-cache-0
          paths:
            - "~/.m2"
            - "~/.sbt"
            - "~/.ivy2/cache"
workflows:
  deployment:
    jobs:
      - publish-and-release:
          filters:
            branches:
              only:
                - master